### ISSUE TITLE
Password without printing mask

### ISSUE THREAD

**Issue by CommanderTvis** [kotlin-inquirer/kotlin-inquirer#10]
Well, I don't have an exact use case, but some commands use password input hiding even the length of the password like `sudo`.

**Comment by YanivGrama** [comment]
Hey @CommanderTvis 
You can try it with `mask=""`

for example:
```
val password: String = KInquirer.promptInputPassword(message = "Enter Your Password:", mask = "")
println("Password: $password")
```
![password](https://user-images.githubusercontent.com/10834856/152756449-0e3d310c-b363-4d07-9e86-409b6986a479.gif)

wdyt?

**Comment by CommanderTvis** [comment]
> 

That's what I meant.
