### ISSUE TITLE
Some unicodes not visible in WSL

### ISSUE THREAD

**Issue by MaaxGr** [kotlin-inquirer/kotlin-inquirer#3]
I am using the windows subsystem for linux and executed `kscript https://git.io/fjj2P`. Unfortunattly some unicodes are not loading. Any workaround/plans for this issue?

![grafik](https://user-images.githubusercontent.com/43404580/104491820-1002a000-55d3-11eb-855d-ff4faff8b77b.png)

**Comment by YanivGrama** [comment]
Hey @MaaxGr 
Thanks for the feedback 🙏 

Check out the latest version 0.1.0
It should work now
