### ISSUE TITLE
WARNING: Unable to create a system terminal, creating a dumb terminal

### ISSUE THREAD

**Issue by theapache64** [kotlin-inquirer/kotlin-inquirer#6]
> WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

I am getting this in my terminal when I try to run the program from `IntelliJ`. Can you tell me the reason for this? and do we have any workaround ?

**Comment by YanivGrama** [comment]
Hey @theapache64 ,
Thank you for using kotlin-inquirer!
I noticed that Intellj's terminal behaves differently from iTerm and I didn't had the time to fix it.
I hope I would get back to it real soon and resolve all of the open issues.

feel free to suggest a PR - it would be much appreciated
🙏

**Comment by YanivGrama** [comment]
Hey,
Please check this related issue
https://github.com/jline/jline3/issues/263

**Comment by YanivGrama** [comment]
Hey,
Please check this related issue
https://github.com/jline/jline3/issues/263
